// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArwS9JQ_7RV89Hj83LNDUI2wwZ-tOxavI',
    appId: '1:935401990529:web:4d787477e73da47fc36080',
    messagingSenderId: '935401990529',
    projectId: 'drivly-dbcc4',
    authDomain: 'drivly-dbcc4.firebaseapp.com',
    storageBucket: 'drivly-dbcc4.appspot.com',
    measurementId: 'G-XH1T8VN5CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLM93uKm4r7wkF-ytfRjTdJp3ZUrAqsIk',
    appId: '1:935401990529:android:717be3f8019ed732c36080',
    messagingSenderId: '935401990529',
    projectId: 'drivly-dbcc4',
    storageBucket: 'drivly-dbcc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vrx6R1AcJ9AezTCCaVK-nobT5en1IX4',
    appId: '1:935401990529:ios:944f085696ccfc8fc36080',
    messagingSenderId: '935401990529',
    projectId: 'drivly-dbcc4',
    storageBucket: 'drivly-dbcc4.appspot.com',
    iosBundleId: 'com.example.drivly2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0vrx6R1AcJ9AezTCCaVK-nobT5en1IX4',
    appId: '1:935401990529:ios:944f085696ccfc8fc36080',
    messagingSenderId: '935401990529',
    projectId: 'drivly-dbcc4',
    storageBucket: 'drivly-dbcc4.appspot.com',
    iosBundleId: 'com.example.drivly2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArwS9JQ_7RV89Hj83LNDUI2wwZ-tOxavI',
    appId: '1:935401990529:web:e3cb11087a806291c36080',
    messagingSenderId: '935401990529',
    projectId: 'drivly-dbcc4',
    authDomain: 'drivly-dbcc4.firebaseapp.com',
    storageBucket: 'drivly-dbcc4.appspot.com',
    measurementId: 'G-HLB8QD6T5S',
  );
}
